### ISSUE TITLE
NoClassDefFoundError: EntityEvent$EyeHeight - NeoForge for 1.20.1

### ISSUE THREAD

**Issue by dogonotoughen** [seymourimadeit/Big-Brain#53]
Minecraft 1.20.1, NeoForge 47.1.106

>[net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: bigbrain, class tallestegg.bigbrain.BigBrain
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityEvent$EyeHeight
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3502) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Class.java:3527) ~[?:?]
	at java.lang.Class.getMethods(Class.java:2112) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.5.jar%23111!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.5.jar%23111!/:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[language-java-47.2.2.jar%23424!/:47.2]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[language-java-47.2.2.jar%23424!/:47.2]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:122) ~[language-java-47.2.2.jar%23424!/:47.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[core-47.2.2.jar%23423!/:47.2]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.EntityEvent$EyeHeight
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 18 more

Something about eye height? a similar issue is marked as resolved. What's going on?

**Comment by seymourimadeit** [comment]
Are you using this version? https://legacy.curseforge.com/minecraft/mc-mods/big-brain/files/5429380

**Comment by dogonotoughen** [comment]
Can't believe I missed that, my fault. Yup that version works perfectly!
