### ISSUE TITLE
Server timing out

### ISSUE THREAD

**Issue by schindlershadow** [seymourimadeit/Big-Brain#55]
server keeps timing out
```
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 180000000.00 seconds (should be max 0.05)
	at java.base/java.util.Collections.shuffle(Collections.java:486) ~[?:?] {re:mixin}
	at java.base/java.util.Collections.shuffle(Collections.java:454) ~[?:?] {re:mixin}
	at java.base/java.util.Collections.shuffle(Collections.java:434) ~[?:?] {re:mixin}
	at TRANSFORMER/bigbrain@2.2.3/tallestegg.bigbrain.common.entity.ai.goals.ParkourGoal.calculateOptimalJumpVector(ParkourGoal.java:167) ~[bigbrain-2.2.3-1.21.jar%23384!/:?] {re:classloading}
	at TRANSFORMER/bigbrain@2.2.3/tallestegg.bigbrain.common.entity.ai.goals.ParkourGoal.pickCandidate(ParkourGoal.java:140) ~[bigbrain-2.2.3-1.21.jar%23384!/:?] {re:classloading}
	at TRANSFORMER/bigbrain@2.2.3/tallestegg.bigbrain.common.entity.ai.goals.ParkourGoal.start(ParkourGoal.java:77) ~[bigbrain-2.2.3-1.21.jar%23384!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.ai.goal.WrappedGoal.start(WrappedGoal.java:41) ~[server-1.21.1-20240808.144430-srg.jar%23362!/:?] {re:classloading,pl:accesstransformer:B}
```
full crash report https://pastebin.com/raw/2tSxWzFN

**Comment by seymourimadeit** [comment]
Turn off parkour ai for now

**Comment by schindlershadow** [comment]
is there a fix in the works?

**Comment by seymourimadeit** [comment]
A more performant method for parkour ai will be in the works the sooner I get more free time on my hands (life is busy !)
